Repository 47degrees/mu-smart-home, pull requests merged in 2020-04, with the labels that each got.

#79 Update actions, documentation templates and configuration files to v0.3.1
  .github/labels.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/bot-prs-auto-approve.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/update-labels.yml
  .gitignore
  .mergify.yml
  docs/AUTHORS.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/LICENSE.md
  docs/NOTICE.md
Labels: auto-update

#80 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#81 Update actions, documentation templates and configuration files to v0.3.2
  .mergify.yml
Labels: auto-update

#82 Update actions, documentation templates and configuration files to v0.4.0
  .github/workflows/bot-prs-auto-approve.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: auto-update

#84 Update actions, documentation templates and configuration files to v0.4.1
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: auto-update

#87 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: auto-update

#85 Update actions, documentation templates and configuration files to v0.5.0
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .mergify.yml
Labels: auto-update

#88 Update sbt to 1.3.10
  project/build.properties
Labels: scala-steward

#89 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#91 Update cats-effect to 2.1.3
  project/ProjectPlugin.scala
Labels: scala-steward

#94 Update sbt-mu-srcgen to 0.21.4
  project/plugins.sbt
Labels: scala-steward
